"""Menu / permission catalogue.

Direct port of App\\Enums\\Permission::grouped() (app/Enums/Permission.php,
lines 417-687) — the MDI menu structure that drives the sidebar. Each leaf is a
permission key; a user is DENIED a key if it appears in userd for their code
(see core.auth.AppSession.can / blocked_items).

Only Phase 1 items have real windows yet; the rest render as disabled
placeholders until their module is ported.
"""

from __future__ import annotations

# group title -> list of permission keys (verbatim from Permission::grouped())
GROUPED: dict[str, list[str]] = {
    "MDI System & Admin": [
        "MDI_DASHBOARD", "MDI_APPLICATION_SETTINGS", "MDI_ADMINISTRATION",
        "MDI_COMPANY_SELECT", "MDI_CUSTOMER_CAMPAIGN", "MDI_USER_ACCESS",
        "MDI_ADMIN_USERS", "MDI_STATES_ADDING", "MDI_AI_INSIGHTS",
        "MDI_PHONE_BOOK", "MDI_TASK_REMINDERS", "MDI_BACKUP",
        "MDI_YEAR_END_ACCOUNT_CLOSE",
    ],
    "MDI Accounts": [
        "MDI_ACCOUNTS_AC_LEDGER", "MDI_ACCOUNTS_CUSTOMER_BILLWISE_RCPT",
        "MDI_ACCOUNTS_SUPPLIER_BILLWISE_PAYMENT", "MDI_ACCOUNTS_DEBIT_CREDIT_NOTE",
        "MDI_ACCOUNTS_RATE_DIFF_ADJUSTMENT", "MDI_ACCOUNTS_GROUP_AMT_ALLOCATION",
        "MDI_ACCOUNTS_CHANGE_DUEDATE", "MDI_ACCOUNTS_RESTART_DATE",
        "MDI_ACCOUNTS_AMT_WGT_TRANSFER", "MDI_ACCOUNTS_PAYMENT_CONFIRMATION",
        "MDI_ACCOUNTS_DENOMINATION_ENTRY", "MDI_ACCOUNTS_EXPENSE_VOUCHER_ENTRY",
        "MDI_ACCOUNTS_PARTY_CODE_MERGE", "MDI_ACCOUNTS_MASTER",
        "MDI_ACCOUNTS_RECEIPT", "MDI_ACCOUNTS_PAYMENT",
        "MDI_ACCOUNTS_SUSPENSE_ENTRY", "MDI_ACCOUNTS_SUSPENSE_MASTER",
        "MDI_ACCOUNTS_EDIT_ENTRY", "MDI_ACCOUNTS_JOURNAL",
        "MDI_ACCOUNTS_PDC_COLLECTION", "MDI_PDC_REPORT", "MDI_ACCOUNTS_DAILY_STATEMENT",
    ],
    "MDI Sales": [
        "MDI_SALES_BILL", "MDI_SALES_BILL_NEW", "MDI_SALES_BILL_EDIT",
        "MDI_SALES_BILL_CANCEL", "MDI_SALES_BILL_PRINT", "MDI_SALES_QUOTATION",
        "MDI_SALES_QUOTATION_EDIT", "MDI_SALES_QUOTATION_CANCEL",
        "MDI_SALES_BILL_CONFIRMATION", "MDI_SALES_BOOK_REPORT",
        "MDI_MONTHLY_SALES_REPORT", "MDI_SALES_REGISTER",
        "MDI_SALESMAN_CATEGORY_REPORT", "MDI_SALES_CHECK_LIST",
        "MDI_SALES_RETURN", "MDI_SALES_RETURN_REGISTER", "MDI_NET_SALES_REPORT",
        "MDI_DELIVERY_STATUS_REPORT", "MDI_POINT_CARD_POINTS_REPORT",
    ],
    "MDI Purchase": [
        "MDI_PURCHASE_BILL", "MDI_PURCHASE_BILL_CONFIRMATION",
        "MDI_PURCHASE_RETURN", "MDI_PURCHASE_CHECK_LIST", "MDI_PURCHASE_BOOK",
        "MDI_PURCHASE_REGISTER", "MDI_PURCHASE_RETURN_REGISTER",
        "MDI_DIAMOND_PURCHASE_BILL", "MDI_DIAMOND_PURCHASE_RETURN",
    ],
    "MDI Stock & Barcode": [
        "MDI_STOCK_OPENING_STOCK", "MDI_STOCK_LEDGER", "MDI_STOCK_PERIOD_LEDGER",
        "MDI_STOCK_ITEM_HISTORY", "MDI_STOCK_REGISTER", "MDI_STOCK_VERIFICATION",
        "MDI_STOCK_SUMMARY_COST_WISE", "MDI_STOCK_SUMMARY_RATE_WISE",
        "MDI_STOCK_SUSPENSE_ENTRY", "MDI_ITEM_STOCK_ADJUSTMENT",
        "MDI_ITEM_STOCK_ADJUSTMENT_MULTI", "MDI_ITEM_STOCK_ADD_LESS",
        "MDI_ITEM_STOCK_ADJUSTMENT_COMPARE", "MDI_BARCODE_SINGLE_ENTRY",
        "MDI_BARCODE_MULTI_ENTRY", "MDI_BARCODE_REGISTER", "MDI_BARCODE_PROFIT",
        "MDI_COUNTER_ISSUE", "MDI_DIAMOND_STONE_STOCK", "MDI_BARCODE_HISTORY",
    ],
    "MDI Orders & Goldsmith": [
        "MDI_ORDER_BILL", "MDI_ORDER_UPDATE", "MDI_ORDER_BLOCK", "MDI_ORDER_SALE",
        "MDI_ORDER_ADVANCE_AFTER", "MDI_ORDER_RATE_FIX", "MDI_ORDER_REPRINT",
        "MDI_ORDER_CANCEL", "MDI_ORDER_PROCESS", "MDI_ORDER_RETURNS",
        "MDI_GOLDSMITH_TRANSACTIONS",
        "MDI_JEWELLERY_TRANSACTIONS", "MDI_PARTY_WGT_DEPOSIT",
        "MDI_GOLD_RATE_STORY", "MDI_WGT_RCPT_PMNT", "MDI_PARTY_OP_WEIGHT",
        "MDI_DEPOSITORS_INT_POST", "MDI_PURITY_TESTING", "MDI_PURITY_CERTIFICATE",
        "MDI_REFINERY_BILL", "MDI_RUFF_WORK", "MDI_OTHER_ITEM_TRANS",
        "MDI_EINVOICE_REGISTER", "MDI_SCHEME_COLLECTION", "MDI_SCHEME_CLOSE",
        "MDI_SCHEME_INTEREST", "MDI_SCHEME_PASSBOOK", "MDI_SCHEME_REFUND",
    ],
    "MDI Customers & Masters": [
        "MDI_CUSTOMER", "MDI_SUPPLIER_MASTER", "MDI_GOLDSMITH_MASTER",
        "MDI_REFINER_MASTER", "MDI_JEWELLERY_MASTER", "MDI_DEPOSITOR_MASTER",
        "MDI_STAFF_MASTER", "MDI_SALESMAN_MASTER", "MDI_CUSTOMER_POPUP",
        "MDI_SEARCH_ITEMS", "MDI_GROUPS", "MDI_SUB_GROUPS", "MDI_PURITY_TYPE",
        "MDI_REGIONAL_HELP", "MDI_ITEM_TEMP", "MDI_ITEM_HELP", "MDI_OTHER_ITEMS",
        "MDI_COUNTERS", "MDI_WASTAGE_TABLE", "MDI_BILL_PREFIX",
        "MDI_PARTY_MC_TABLE", "MDI_MC_TABLE", "MDI_GIFT_TABLE", "MDI_POINT_CARD",
        "MDI_DENOMINATION_MASTER", "MDI_OP_BILL_CREATION_CUSTOMERS",
        "MDI_ITEM_MASTER", "MDI_STOCK_TYPE", "MDI_MODEL_MASTER", "MDI_REORDER",
        "MDI_RATE_UPDATE", "MDI_RATE_HISTORY", "MDI_KURI_DETAILS",
        "MDI_KURI_TYPE_MASTER", "MDI_ALLOYS", "MDI_FASHION", "MDI_AREA",
        "MDI_ROUTE",
    ],
    "MDI Reports & Books": [
        "MDI_DAYBOOK", "MDI_DAY_SUMMARY", "MDI_MARKED_LIST", "MDI_MC_PROFIT",
        "MDI_VA_CHECK_LIST", "MDI_VA_CHECK_REPORT", "MDI_FINANCIAL_STATEMENTS",
        "MDI_SMITH_BOOK", "MDI_TAX_PURCHASE_BOOK", "MDI_JEWLLERY_BOOK",
        "MDI_OUTSTANDING_TAX", "MDI_TDS_REPORT", "MDI_FINANCIAL_REPORTS", "MDI_BARCODE_REPORTS",
        "MDI_CUSTOMER_ANALYTICS", "MDI_DEPOSIT_ANALYTICS",
        "MDI_GOLDSMITH_ANALYTICS", "MDI_SMITH_LOT_REPORT", "MDI_GST_TAX_REPORTS", "MDI_INVENTORY_REPORTS",
        "MDI_JEWELLERY_ANALYTICS", "MDI_ORDER_ANALYTICS",
        "MDI_OTHER_ITEM_REPORTS", "MDI_OTHER_REPORTS", "MDI_CHITTY_ANALYTICS",
        "MDI_STAFF_ANALYTICS", "MDI_SUPPLIER_ANALYTICS", "MDI_REFINERY_ANALYTICS",
        "MDI_REPAIR_ANALYTICS",
    ],
    "MDI New Modules": [
        "MDI_WHATSAPP_GATEWAY", "MDI_GSTR_REPORTS", "MDI_GOLD_LOAN",
        "MDI_CATALOGUE", "MDI_TALLY_EXPORT", "MDI_HALLMARK", "MDI_STAFF_PAYROLL",
        "MDI_BRANCH_MANAGEMENT", "MDI_SCALE_SETTINGS",
    ],
    "MDI Staff & Repair": [
        "MDI_STAFF_TRANSACTION", "MDI_STAFF_LOG_UPDATE", "MDI_STAFF_LEAVE_ENTRY",
        "MDI_STAFF_WGT_TRANSACTION", "MDI_REPAIR_COMPLAINTS",
        "MDI_REPAIR_RECEIPT_MEMO_PARTY", "MDI_REPAIR_SMITH_MEMO",
        "MDI_REPAIR_ISSUE_MEMO_PARTY", "MDI_REPAIR_RETURN",
    ],
}

# Friendly labels for the items Phase 1 actually wires up. Everything else is
# humanised on the fly (label_for) until its module is ported.
LABELS: dict[str, str] = {
    "MDI_DASHBOARD": "Dashboard",
    "MDI_APPLICATION_SETTINGS": "Application Settings",
    "MDI_COMPANY_SELECT": "Company Select",
    "MDI_USER_ACCESS": "User Access",
    "MDI_ADMINISTRATION": "Administration",
    "MDI_BACKUP": "Data Backup & Restore",
}


def label_for(key: str) -> str:
    if key in LABELS:
        return LABELS[key]
    text = key[4:] if key.startswith("MDI_") else key
    return text.replace("_", " ").title()


def all_keys() -> list[str]:
    return [k for keys in GROUPED.values() for k in keys]
